# action.yml
name: 'Detect SATDs'
description: 'SATDs detection'
author: feilerdev

inputs:
  input_output_path:
    description: 'Path where the report will be generated'
    required: false
    default: './report'

outputs:
  exported_csv:
    description: "Returns default CSV with detected SATDs."

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_OUTPUT_PATH: ${{ inputs.output_path }}

branding:
  icon: file-text
  color: red
