# action.yml
name: 'Detect SATDs'
description: 'SATDs detection'
author: feilerdev

inputs:
  output_path:
    description: 'Path where the report will be generated'
    required: false
    default: './report'

outputs:
  exported_csv:
    description: "Returns default CSV wit detected SATDs."

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output_format }}
    - ${{ inputs.output_path }}

branding:
  icon: file-text
  color: red
