# action.yml
name: 'Detect SATDs'
description: 'SATDs detection'
author: feilerdev

inputs:
  workspace_path:
    description: 'Workspaces path, its where the code will be scanned'
    required: false
    default: '.'
  ignore_path:
    description: 'Path not scanned'
    required: false
    default: 'vendor'
  output_path:
    description: 'Path where the report will be generated'
    required: false
    default: './reports'

outputs:
  exported_csv:
    description: "Returns default CSV with detected SATDs."

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WORKSPACE_PATH: ${{ inputs.workspace_path }}
    IGNORE_PATH: ${{ inputs.ignore_path }}
    OUTPUT_PATH: ${{ inputs.output_path }}

branding:
  icon: file-text
  color: red
